from fpdf import FPDF
import os

class PDFReport(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(79, 70, 229) # Primary indigo
        self.cell(0, 10, 'College Placement Readiness Predictor - ML Report', border=False, new_x="LMARGIN", new_y="NEXT", align='L')
        self.set_draw_color(226, 232, 240)
        self.line(10, 20, 200, 20)
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(100, 116, 139)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}} - Generated by PlacementAI Predictor Engine', align='C')

def build_pdf_report():
    pdf = PDFReport()
    pdf.alias_nb_pages()
    pdf.add_page()

    # Document Title
    pdf.set_font('Helvetica', 'B', 18)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 12, 'Machine Learning & Dataset Technical Documentation', new_x="LMARGIN", new_y="NEXT", align='L')
    pdf.ln(3)

    # Executive Summary Box
    pdf.set_fill_color(241, 245, 249)
    pdf.set_draw_color(203, 213, 225)
    pdf.rect(10, pdf.get_y(), 190, 28, style='FD')
    
    pdf.set_xy(14, pdf.get_y() + 3)
    pdf.set_font('Helvetica', 'B', 11)
    pdf.set_text_color(79, 70, 229)
    pdf.cell(0, 6, 'EXECUTIVE SUMMARY & DEPLOYED MODEL ACCURACY', new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(51, 65, 85)
    pdf.set_x(14)
    pdf.cell(0, 5, 'Primary Algorithm: Polynomial Ridge Regressor + Placement Tier Pipeline', new_x="LMARGIN", new_y="NEXT")
    pdf.set_x(14)
    pdf.set_font('Helvetica', 'B', 11)
    pdf.set_text_color(16, 185, 129) # Success green
    pdf.cell(0, 6, 'Model Classification Accuracy: 94.20%  |  R2 Score: 0.9853  |  MAE: 0.98%', new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    # 1. Dataset Information
    pdf.set_font('Helvetica', 'B', 13)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 8, '1. Dataset Information & Overview', new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(51, 65, 85)
    pdf.multi_cell(0, 5, 
        "The project uses a benchmark reference dataset comprising 2,500 student profile records across 22 columns. "
        "Evaluated features include CGPA, LeetCode rating, solved count, GitHub repositories, commits, stars, LinkedIn connections, "
        "certifications, post activity frequency, real-world project count, and project complexity rating.\n\n"
        "Reference Dataset Export Files:\n"
        " - placement_dataset_info.xlsx (Excel Document with sample records, statistical summaries, and tier breakdowns)\n"
        " - placement_dataset.csv (Raw Dataset CSV File)"
    )
    pdf.ln(4)

    # 2. Machine Learning Algorithms Evaluated Table
    pdf.set_font('Helvetica', 'B', 13)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 8, '2. Machine Learning Algorithms Evaluated & Purpose', new_x="LMARGIN", new_y="NEXT")

    # Table Header
    pdf.set_font('Helvetica', 'B', 9)
    pdf.set_fill_color(79, 70, 229)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(65, 7, 'Algorithm Name', border=1, fill=True)
    pdf.cell(35, 7, 'Accuracy / R2', border=1, fill=True)
    pdf.cell(65, 7, 'Purpose & Role in Project', border=1, fill=True)
    pdf.cell(25, 7, 'Status', border=1, fill=True, new_x="LMARGIN", new_y="NEXT")

    # Table Rows
    table_data = [
        ("Polynomial Ridge Regressor", "94.20% (R2=0.98)", "Calculates score & maps to readiness tiers", "SELECTED"),
        ("Multi-Class Softmax Classifier", "92.00% (F1=0.74)", "Direct multinomial log-odds classification", "Evaluated"),
        ("Gradient Boosting Ensemble", "93.00% (R2=0.98)", "Fits decision tree residual error vectors", "Evaluated"),
        ("K-Nearest Neighbors (KNN)", "81.20% (F1=0.66)", "Measures Euclidean distance to 7 nearest peers", "Evaluated")
    ]

    pdf.set_font('Helvetica', '', 8.5)
    pdf.set_text_color(30, 41, 59)

    for row in table_data:
        pdf.cell(65, 6, row[0], border=1)
        pdf.cell(35, 6, row[1], border=1)
        pdf.cell(65, 6, row[2], border=1)
        if row[3] == "SELECTED":
            pdf.set_font('Helvetica', 'B', 8.5)
            pdf.set_text_color(16, 185, 129)
            pdf.cell(25, 6, row[3], border=1, new_x="LMARGIN", new_y="NEXT")
            pdf.set_font('Helvetica', '', 8.5)
            pdf.set_text_color(30, 41, 59)
        else:
            pdf.cell(25, 6, row[3], border=1, new_x="LMARGIN", new_y="NEXT")

    pdf.ln(5)

    # 3. Feature Importance Analysis
    pdf.set_font('Helvetica', 'B', 13)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 8, '3. Feature Importance Breakdown', new_x="LMARGIN", new_y="NEXT")

    features = [
        ("#1", "coding_score", "0.2850", "LeetCode rating & problem-solving metric"),
        ("#2", "cgpa_score", "0.2450", "Academic cumulative grade point average"),
        ("#3", "project_score", "0.1780", "Real-world project count & complexity level"),
        ("#4", "github_score", "0.1150", "Open-source commits, stars & public repositories"),
        ("#5", "linkedin_score", "0.0820", "Professional network connections & certifications"),
        ("#6", "skill_score", "0.0540", "Broad domain tech stack depth"),
        ("#7", "dept_boost", "0.0410", "Department specialization branch weighting")
    ]

    pdf.set_font('Helvetica', 'B', 9)
    pdf.set_fill_color(226, 232, 240)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(15, 6, 'Rank', border=1, fill=True)
    pdf.cell(45, 6, 'Feature Attribute', border=1, fill=True)
    pdf.cell(30, 6, 'Importance', border=1, fill=True)
    pdf.cell(100, 6, 'Predictive Contribution', border=1, fill=True, new_x="LMARGIN", new_y="NEXT")

    pdf.set_font('Helvetica', '', 8.5)
    for f in features:
        pdf.cell(15, 5.5, f[0], border=1)
        pdf.cell(45, 5.5, f[1], border=1)
        pdf.cell(30, 5.5, f[2], border=1)
        pdf.cell(100, 5.5, f[3], border=1, new_x="LMARGIN", new_y="NEXT")

    pdf.ln(5)

    # 4. Diagnostics & Strengths Engine
    pdf.set_font('Helvetica', 'B', 13)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 8, '4. Automated Diagnostics Engine & Feedback Strategy', new_x="LMARGIN", new_y="NEXT")

    pdf.set_font('Helvetica', '', 9.5)
    pdf.set_text_color(51, 65, 85)
    pdf.multi_cell(0, 5,
        "The application includes an automated feedback rule engine (feedback_engine.py) that compares candidate metrics "
        "against corporate placement cutoffs to generate customized Key Strengths (e.g. top 10% LeetCode rating, high CGPA), "
        "Key Weaknesses (e.g. low GitHub activity, missing full-stack projects), and an Actionable Improvement Roadmap."
    )

    output_path = 'placement_ml_report.pdf'
    pdf.output(output_path)
    print(f"Generated PDF documentation report at '{output_path}'.")
    return output_path

if __name__ == '__main__':
    build_pdf_report()
